---
version: '2'
services:
  mongo:
    image: mongo
    expose:
    - "27017"

  mariadb:
    build: test/mariadb
    expose:
    - "3306"

  rtrn:
    build:
      context: .
      dockerfile: test/rtrn/Dockerfile
      args:
      - HTTP_PROXY=$DOCKER_HTTP_PROXY
      - HTTPS_PROXY=$DOCKER_HTTPS_PROXY
      - NO_PROXY=$DOCKER_NO_PROXY
    depends_on:
    - mongo
    - mariadb

